# Generated by Django 3.1.3 on 2020-11-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_auto_20201128_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlobject',
            name='short_path',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
