# Generated by Django 3.1.3 on 2020-12-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0004_auto_20201129_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlobject',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
